### ISSUE TITLE
watchdog kill bugs

### ISSUE THREAD

**Issue by walterdejong** [mej/nhc#13]
The `nhc` script has a watchdog timer that uses a construct like

    kill pid || return 0

and then proceeds to kill some more if it fails. Well, it always proceeds because in the bash shell a zero return is actually true. So me thinks the killing lines should read

    kill pid && return 0

I tested this on a code snippet and indeed, killing the watchdog works fine with `&&` rather than `||`.
The easiest way to see this for yourself is to try something like this in a shell:

    sleep 60 &
    kill $! || echo hello

vs

    sleep 60 &
    kill $! && echo hello

I'm too lazy this morning to make a fork + pull request for this. The statements to fix are in `nhc` functions `nhcmain_watchdog_timer` and `kill_watchdog`.

Hope this helps, and thanks for `nhc` !

**Comment by mej** [comment]
Thanks for your report, Walter!

The code is correct as written.  The `kill` command in `bash` returns 0 on success, yes, but success in this case doesn't mean the process went away.  It simply means that the signal was successfully delivered to the process(es) specified.  From the `bash(1)` man page:

    kill returns true if at least one signal was successfully sent, or false if an error occurs or an invalid option is encountered.

In particular, "successfully sent" means that there was a process with the specified PID which was able to receive the signal.  A non-zero return value, for our purposes, means that the specified process is no longer there to receive the signal -- i.e., it's already been successfully killed.

NHC uses the `|| return 0` you noted in the code to handle the case where either the process went away on its own, or NHC's previous attempt(s) to terminate it were successful, so it doesn't need to continue trying to `kill` (i.e., signal) it.  If the invocation of `kill` succeeds, then the process is still there, so NHC might not have successfully gotten it to die yet and must therefore keep trying.  Just because `kill` returns success doesn't mean the process *actually died*, though.  It only means that the signal was delivered.

Make sense?

**Comment by walterdejong** [comment]
Yes, so true.

Thanks!



On Wed, Mar 30, 2016 at 8:50 PM, Michael Jennings <notifications@github.com>
wrote:

> Thanks for your report, Walter!
>
> The code is correct as written. The kill command in bash returns 0 on
> success, yes, but success in this case doesn't mean the process went away.
> It simply means that the signal was successfully delivered to the
> process(es) specified. From the bash(1) man page:
>
> kill returns true if at least one signal was successfully sent, or false if an error occurs or an invalid option is encountered.
>
> In particular, "successfully sent" means that there was a process with the
> specified PID which was able to receive the signal. A non-zero return
> value, for our purposes, means that the specified process is no longer
> there to receive the signal -- i.e., it's already been successfully killed.
>
> NHC uses the || return 0 you noted in the code to handle the case where
> either the process went away on its own, or NHC's previous attempt(s) to
> terminate it were successful, so it doesn't need to continue trying to
> kill (i.e., signal) it. If the invocation of kill succeeds, then the
> process is still there, so NHC might not have successfully gotten it to die
> yet and must therefore keep trying. Just because kill returns success
> doesn't mean the process *actually died*, though. It only means that the
> signal was delivered.
>
> Make sense?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/mej/nhc/issues/13#issuecomment-203576565>
>



-- 
***
If a woodchuck could chuck wood, and a woodchuck would chuck wood,
how much wood would a woodchuck chuck?
