### ISSUE TITLE
NHC "Negate" Check for NVIDIA Thermal Slowdowns Not Working

### ISSUE THREAD

**Issue by b0x68** [mej/nhc#150]
Hi,

I've implemented a function to check for NVIDIA GPU thermal slowdowns. I've tried to negate a group of servers in the syntax format of !/node\d\d\d/  || check_nv_smi_thermal_slowdowns. However, when I run my SLURM command to view draining/drain/down nodes, I see a constant set of these negated nodes showing up in draining state. Any ideas what I'm doing wrong?

```
# dnf info lbnl-nhc
Last metadata expiration check: 3:13:08 ago on Fri 16 Aug 2024 08:39:56 AM EDT.
Installed Packages
Name         : lbnl-nhc
Version      : 1.4.3

OS: RHEL9.4
```

custom.nhc
```
function check_nv_smi_thermal_slowdowns() {
	expected_count=0
	actual_count="$(nvidia-smi --query-gpu=clocks_event_reasons.hw_thermal_slowdown,clocks_event_reasons.sw_thermal_slowdown --format=csv,noheader | egrep -v 'Not Active, Not Active' |grep Active |wc -l)"
	if [ $expected_count -ne $actual_count ]; then
        die 1 "$actual_count GPUs indicate thermal slowdowns"
		return 1
	fi
    return 0
}
```

```
[root@headnode nhc]# pwd
/etc/nhc
[root@headnode nhc]# tree
.
├── 1
├── nhc.conf
└── scripts
    ├── common.nhc
    ├── custom.nhc
    ├── lbnl_cmd.nhc
    ├── lbnl_dmi.nhc
    ├── lbnl_file.nhc
    ├── lbnl_fs.nhc
    ├── lbnl_gpu.nhc
    ├── lbnl_hw.nhc
    ├── lbnl_job.nhc
    ├── lbnl_moab.nhc
    ├── lbnl_net.nhc
    ├── lbnl_nv.nhc
    └── lbnl_ps.nhc

1 directory, 15 files
```
nhc.conf
excerpt of nhc.conf for thermal_nv_smi_slowdowns

 ```
  /node017/    || check_nv_smi_thermal_slowdowns
  /node018/    || check_nv_smi_thermal_slowdowns
  /node019/    || check_nv_smi_thermal_slowdowns
  !/node020/   || check_nv_smi_thermal_slowdowns
  !/node021/   || check_nv_smi_thermal_slowdowns
  !/node022/   || check_nv_smi_thermal_slowdowns
  !/node023/   || check_nv_smi_thermal_slowdowns
  !/node024/   || check_nv_smi_thermal_slowdowns
  !/node025/   || check_nv_smi_thermal_slowdowns
  !/node026/   || check_nv_smi_thermal_slowdowns
  /node027/    || check_nv_smi_thermal_slowdowns
  /node028/    || check_nv_smi_thermal_slowdowns
  /node029/    || check_nv_smi_thermal_slowdowns
  /node030/    || check_nv_smi_thermal_slowdowns
  /node031/    || check_nv_smi_thermal_slowdowns
  !/node101/   || check_nv_smi_thermal_slowdowns
  !/node102/   || check_nv_smi_thermal_slowdowns
  !/node103/   || check_nv_smi_thermal_slowdowns
  !/node104/   || check_nv_smi_thermal_slowdowns
  /node105/    || check_nv_smi_thermal_slowdowns
  /node200/    || check_nv_smi_thermal_slowdowns
  /node201/    || check_nv_smi_thermal_slowdowns
  /node202/    || check_nv_smi_thermal_slowdowns
```

```
node104     draining    "partition"         NHC: check_nv_smi_temp: At least 3 GPUs are overheated                     2024-08-16T12:25:27
node102     draining    "partition"         NHC: check_nv_smi_temp: At least 3 GPUs are overheated                     2024-08-16T12:40:24
node103     draining    "partition"         NHC: check_nv_smi_temp: At least 3 GPUs are overheated                     2024-08-16T12:45:25
node907     draining    "partition"         NHC: check_nv_smi_temp: At least 3 GPUs are overheated                     2024-08-16T13:10:19
```

As a workaround, I've simply removed those nodes from the check, but was hoping to do it with a regex pattern.

**Comment by mej** [comment]
The relationship between a normal match string and a negated match string is analogous to the relationship between an AND gate and a NAND gate.  (If you're not familiar with logic gates, or if you need a refresher, [TechTarget](https://www.techtarget.com/whatis/definition/logic-gate-AND-OR-XOR-NOT-NAND-NOR-and-XNOR) and [Geeks for Geeks](https://www.geeksforgeeks.org/implementation-and-from-nand/) both have pretty good (i.e., clear, concise, and accurate) writeups on the concepts.)  Specifically, just like a NAND gate is simply an AND gate with an inverter (or NOT gate, if you prefer) on the output path, in NHC, having the leading `!` does not affect how the "match" operation is performed; all it does is negate the result, just like a NOT gate.  It just "flips the bit," so to speak, transforming "true" to "false" and "false" to "true."

When NHC reads its config file, it evaluates the match string (I typically use "**`mstr`**" as shorthand for "match string") on the left-hand side (LHS) of the `||` delimiter on each (non-comment) line, one-by-one.  If the `mstr` evaluates to "true" on a particular line, the right-hand side (RHS) -- i.e., everything to the right of the first `||` on the line -- gets stored in an array variable comprising the list of checks that will be run.

Understanding all of that, let's now step through what's going on.  Looking at the `nhc.conf` excerpt you provided, we can see based on their regex `mstr`'s that the first 3 lines will run your `check_nv_smi_thermal_slowdowns()` check on any host whose name contains `node017`, `node018`, and `node019`, respectively.  That's exactly what one would expect, so that tracks. 👍 

But now when we get to the 4th line, we see the `mstr` "`!/node020/`" there on the LHS.  This `mstr` is a negated regular expression match of the hostname to the exact string `node020`, and since it's not bound to the start/end of the value (in other words, the regular expression neither starts with `^` nor ends with `$`), the string `node020` will match anywhere in the value -- in this case, the hostname.  So any system named `node020`, `computenode02015`, `mycluster-node020-row01cab12slt30`, `spinode02024`, `palinode02012024`, ...you get the idea 😉...will match.  Since the `mstr` is negated, though, the check will run iff (short for "if and only if") the hostname does **not** contain `node020`.  So the entire `mstr` as a whole ("`!/node020/`") evaluates to "false" on `node020`...but it evaluates to "true" on `node017`, `node018`, `node021`, `node101`, `node202`, and all the others.  So that 4th line will -- as was intended, I believe -- prevent the GPU check from running on `node020` _due to that line_, but it will also cause the check to run everywhere else.  That means nodes 17, 18, and 19 will all run it again, as will nodes 21 through 202.

What happens on the 5th line?  The `mstr` on that line is `!/node021/`, so that line will cause NHC to invoke `check_nv_smi_thermal_slowdowns()` on all of your nodes -- again! -- except node 21.  It will call that same check again on line 6 (except for node 22, of course), and again on line 7 (excluding node 23), and so on.

That's why nodes like 102-104 are still being drained by NHC:  Your check is running **_at least once_** on every single node in your cluster (not to mention a dozen or so times on any node where that check passes when executed). 😭 

How to fix this?  Well, you have a few options, but I think your best path forward is to use the "node range" syntax for your `mstr`.  If you prefer to stick with regex's, you can -- the important thing is this:  if you use a negated `mstr`, you should only have ONE of them so that you don't run into the above issue.  For example, `!/^node(02[0-6]|10[1-4])$/` should work (modulo any typos...I haven't tested that).

But personally, I tend to prefer the range syntax; I find it easier to read.  I also recommend against using negated `mstr`'s for exactly the reason you ran into -- the results are seldom what was intended.  So if it were me, I'd pick one of the following two options:

```
{node0[17-19],node0[27-31],node105,node2[00-03]} || check_nv_smi_thermal_slowdowns
```

```
{node0[17-19]} || check_nv_smi_thermal_slowdowns
{node0[27-31]} || check_nv_smi_thermal_slowdowns
     {node105} || check_nv_smi_thermal_slowdowns
{node2[00-03]} || check_nv_smi_thermal_slowdowns
```

Either one will work, so you can choose whatever way is most readable/maintainable for yourself/your team. 😄 

Hope that helps!

**Comment by b0x68** [comment]
Thank you for the thorough explanation! Much appreciated!
