### ISSUE TITLE
Slurm resource manager detected incorrectly as NHC_RM="pbs"

### ISSUE THREAD

**Issue by OleHolmNielsen** [mej/nhc#20]
I've installed the RPM lbnl-nhc-1.4.2-1.el7.noarch.rpm on a new cluster which is using the SLURM resource manager. The NHC_RM is unfortunately autodetected as "pbs" because function nhcmain_find_rm() contains this code:
    # Search PATH for commands
    if type -a -p -f -P pbsnodes >&/dev/null ; then
        NHC_RM="pbs"
The problem is that the SLURM (current version 16.05.2) RPM package "slurm-torque" contains a file /usr/bin/pbsnodes for convenience/compatibility reasons.
My suggestion is to replace "pbsnodes" in  function nhcmain_find_rm() by "qmgr" which presumably wouldn't exist on a SLURM system:
    if type -a -p -f -P qmgr >&/dev/null ; then
        NHC_RM="pbs"

**Comment by mej** [comment]
Apologies for the delay; I'm just now getting out from under the pile of e-mail that accumulated during my vacation!  :-)

If `qmgr` is a better indicator, I'm happy to switch to using that instead, but it's also not uncommon for folks to have SLURM installed alongside TORQUE or another RM during transitions.  So perhaps SLURM detection should come first as well.

If you'd like, please feel free to submit a PR for this change against the `dev` branch; otherwise, I'm happy to make the change.  :-)

**Comment by mej** [comment]
Did you want to put together a PR, or should I go ahead and fix it directly?  Do you have a preference?

**Comment by OleHolmNielsen** [comment]
Hi Michael,

I'm on vacation, and I won't have time to figure out how to submit a PR. 
  I'd appreciate it if you could decide the best solution.

Thanks,
Ole

On 12-08-2016 08:43, Michael Jennings wrote:
> Did you want to put together a PR, or should I go ahead and fix it
> directly? Do you have a preference?


-- 
Ole Holm Nielsen
Department of Physics, Technical University of Denmark,
Building 307, DK-2800 Kongens Lyngby, Denmark
E-mail: Ole.H.Nielsen@fysik.dtu.dk
Homepage: http://dcwww.fysik.dtu.dk/~ohnielse/
Tel: (+45) 4525 3187 / Mobile: (+45) 5180 1620 / Fax: (+45) 4593 2399
