### ISSUE TITLE
syntax error: invalid arithmetic operator from `   * || check_ps_service -u root -S sshd`

### ISSUE THREAD

**Issue by barrymoo** [mej/nhc#25]
I haven't spent a ton of time with NHC, but I am finding one of the default NHC tests isn't working on my system.

Test is: `   * || check_ps_service -u root -S sshd`
Error is:  `/etc/nhc/scripts/common.nhc: line 381: IntelOPA-Basic.RHEL72-x86_64.10.1.1.0.9: syntax error: invalid arithmetic operator (error token is ".RHEL72-x86_64.10.1.1.0.9")`

Does this mean anything to you? I commented the test out, but at some point I would like to start building up the tests at our center. This one is obviously basic.

**Comment by mej** [comment]
Without knowing what line 381 of `common.nhc` is in your version of NHC, I really can't say.  The error basically means something is being treated as a number but isn't one, namely `.RHEL72...`.  Do you know what that comes from?  I recognize that it's something related to OmniPath, but I haven't seen that particular string before.

**Comment by barrymoo** [comment]
Okay, so I have time to look at this again. First, I realized I installed the `*.el6.*` version so I upgraded using `lbnl-nhc-1.4.2-1.el7.noarch.rpm`. Line 381 of `common.nhc` is Line 12 below:

```
  1 function nhc_common_parse_passwd_entry() {                                
  2     local IFS=':'                                                         
  3     local PASSWD_ENTRY="$1"                                               
  4     local UID_VAR="$2"                                                    
  5     local THIS_UID                                                        
  6     local -a LINE                                                         
  7                                                                           
  8     LINE=( $PASSWD_ENTRY )                                                
  9     THIS_UID=${LINE[2]}                                                   
 10     PWDATA_UIDS[${#PWDATA_UIDS[*]}]=$THIS_UID                             
 11     PWUID_USER[$THIS_UID]="${LINE[0]}"                                    
 12     PWUID_GID[$THIS_UID]=${LINE[3]}                                       
 13     PWUID_GECOS[$THIS_UID]="${LINE[4]}"                                   
 14     PWUID_HOME[$THIS_UID]="${LINE[5]}"                                    
 15     PWUID_SHELL[$THIS_UID]="${LINE[6]}"                                   
 16                                                                           
 17     PWDATA_USERS[${#PWDATA_USERS[*]}]="${LINE[0]}"                        
 18     if [[ $THIS_UID -lt 100 ]]; then                                      
 19         PWDATA_SYSTEM_USERS[${#PWDATA_SYSTEM_USERS[*]}]="${LINE[0]}"      
 20     fi                                                                    
 21     PWDATA_USERID_MAP="$PWDATA_USERID_MAP||${LINE[0]}:$THIS_UID"          
 22     if [[ -n "$UID_VAR" ]]; then                                          
 23         eval $UID_VAR=$THIS_UID                                           
 24     fi                                                                    
 25 }                                                                         
```

The following directory exists: `/root/IntelOPA-Basic.RHEL72-x86_64.10.1.1.0.9`. Looking at that function name and code, I don't see how it ends up with that error.

**Comment by mej** [comment]
What happens if you put quotes around the part after the equals sign, like so:

```bash
PWUID_GID[$THIS_UID]="${LINE[3]}"
```

Does that improve things at all?

**Comment by barrymoo** [comment]
I tried that and adding quotes on Line 9 (above). I guess if it's complaining about 11 (above), something is going on with Line 10 (above)? I tried to `echo ${PWDATA_UIDS[@]}`, but it doesn't print to command line or to `/var/log/nhc.log`. Any thoughts?

**Comment by bbenedetto** [comment]
I'm seeing the same issue with the latest zipfile.

It looks to me like it crashes on lines that have an "*" for the password entry in /etc/passwd.
If I change those to "x" (as a test), then everything works.
But I still haven't figured out WHY it is doing this.

**Comment by bbenedetto** [comment]
Huh.  I fixed it by changing this line in common.nhc:
    LINE=( $PASSWD_ENTRY )
to:
    LINE=( "$PASSWD_ENTRY" )
and it still SEEMS to work....

**Comment by mej** [comment]
That's very strange.  That should **not** be the case -- `bash` isn't supposed to do word splitting on double-quoted strings.

If you look at the code for `nhc_common_parse_passwd_entry()` that you supplied in your earlier comment, you see that the special shell variable `$IFS` is being set to `:` (a single colon).  This allows the line in question (line 8 above) to split the `passwd` file entry into its component parts.  Splitting `$PASSWD_ENTRY` on colons should create an array with 7 entries -- one for each `/etc/passwd` field.  However, if it's double-quoted like you suggest, only 1 field will result.

Unless there's a bug in `bash`, you should be able to see this by doing the following:

``` bash
bash$ (IFS=: ; PASSWD_ENTRY="a:*:c:d:e:f:g" ; FOO=( "$PASSWD_ENTRY" ) ; IFS=$' \t\n' ; echo "FOO (${#FOO[*]}):  ${FOO[*]}")
FOO (1):  a:*:c:d:e:f:g
```

I'm not sure why it worked for you; it shouldn't have.  As you can see above, the `$FOO[]` array only contains 1 element, the original string, and the colons are still intact.

The issue you're seeing is that pathname expansion occurs after all other expansions, including variable expansion and word splitting.  So if there are files in the directory where NHC runs, the "word" which consists of `*` gets replaced by multiple words, one for each file in the directory, as shown here:

``` bash
bash$ (IFS=: ; PASSWD_ENTRY="a:*:c:d:e:f:g" ; FOO=( $PASSWD_ENTRY ) ; IFS=$' \t\n' ; echo "FOO (${#FOO[*]}):  ${FOO[*]}")
FOO (10):  a file1 file2 file3 file4 c d e f g
```

The solution is to turn off pathname expansion altogether, like this:

``` bash
bash$ (set -f ; IFS=: ; PASSWD_ENTRY="a:*:c:d:e:f:g" ; FOO=( $PASSWD_ENTRY ) ; IFS=$' \t\n' ; echo "FOO (${#FOO[*]}):  ${FOO[*]}")
FOO (7):  a * c d e f g
```

I'm currently working on a patch which will disable it globally and only re-enable it in the specific locations where it's needed.  It's not a massive change, but it's also not what I would call "trivial" either, so it will require some testing!  I'll post another update when the patch is ready.  :-)

Thanks for the report!

**Comment by mej** [comment]
As you can see above, I just pushed a commit that will hopefully rectify the situation.  If you don't mind checking out the `glob-disable` branch I just pushed (mej/nhc@8fa6657) and testing to see if that fixes the problem (and making sure everything else still works!), I would definitely appreciate the assistance.  :-)

**Comment by bbenedetto** [comment]
>>> Michael Jennings writes:

  Michael> As you can see above, I just pushed a commit that will hopefully
  Michael> rectify the situation.  If you don't mind checking out the
  Michael> `glob-disable` branch I just pushed (mej/nhc@8fa6657) and
  Michael> testing to see if that fixes the problem (and making sure
  Michael> everything else still works!), I would definitely appreciate the
  Michael> assistance.  :-)

Sorry it took so long to reply.  I've was busy with other crap last week.
This week I decided to pound on this but I didn't know how to clone a
particular git branch as I do not know how to use git (yet).

Then there is an error in the new code that was throwing me off.  I've been
working on it this week but kept getting stuck since I thought the problem
was somewhere in the passwd code still.  But last night it finally occurred
to me where the problem might be.  And this morning I found it.

The code you changed in dealing with the passwd file seems to work. Thanks!

However, a change in the nhc_ps_gather_data function in lbnl_ps.nhc had a
missing line.  That was causing some weird subscript problems which I
assumed were related still to the passwd issue we started with.  Nope.

In nhc_ps_gather_data you commented out this line (69):
        #LINE=( ${LINES[$i]//\*/\\\*} )
but the rest of the function relies on $LINE existing.  And it doesn't.

So I added this line:
        LINE=( ${LINES[$i]} )
And now it works.

Thanks!

-- 
- Bill
+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+
Bill Benedetto     <bbenedetto@goodyear.com>    The Goodyear Tire & Rubber Co.
I don't speak for Goodyear and they don't speak for me.  We're both happy.

**Comment by mej** [comment]
You're absolutely right!  My apologies for that thinko (and for the amount of time it sounds like you spent trying to track it down)!  :-(

I'm happy to push that fix into the `glob-disable` branch this evening after work, or if you'd like to submit a PR for that, I'll gladly take it.

**Comment by bbenedetto** [comment]
>>> Michael Jennings writes:

  Michael> You're absolutely right!  My apologies for that thinko (and for
  Michael> the amount of time it sounds like you spent trying to track it
  Michael> down)!  :-(
  Michael> 
  Michael> I'm happy to push that fix into the `glob-disable` branch this
  Michael> evening after work, or if you'd like to submit a PR for that,
  Michael> I'll gladly take it.

I'm not opposed to submitting a PR, but I'd have to know what a PR is.

I would guess Pull Request.  But I don't know what that means as I don't
speak git.  Sorry.

If how to submit a PR is easily communicated to me (specifically what to do,
that is :-), I will give it a try.

Thanks!

- Bill

**Comment by mej** [comment]
Oops, I missed the notification that you'd replied.  Doh!  :-(

Yes, PR means Pull Request.  But in order to submit a Pull Request, you'd need to fork my NHC repository to one of your own, `git clone` yours from GitHub to your local machine, make the change to your local copy and commit it, push your repo back up to GitHub, and then submit the Pull Request to my NHC tree from yours.

And of course all that requires that you speak Git.  :-)

If you want to learn, the GitHub folks have lots of great Help articles to guide you through the process, starting here:  https://help.github.com/categories/collaborating-with-issues-and-pull-requests/

But if you're not comfortable with Git, I can just go ahead and push the change myself.  No worries!
