### ISSUE TITLE
nhc.conf

### ISSUE THREAD

**Issue by sunyi000** [mej/nhc#27]
Hi,

I'm not sure if this is the right place to ask.

I added additional 2 compute nodes to my existing slurm cluster, and installed all required software, nhc, slurm etc using ansible on the 2 new nodes, but all the 2 new nodes showing 'drain' status because of NHC:check_fs_mount . /run/user/1000 not mounted error. 

Then I found out that on  the 2 new nodes, there's below line in nhc.conf

testnode 1 || check_fs_mount_rw -t "tmpfs" -s "tmpfs" -f "/run/user/1000"

I commented this line out and the 2 new nodes went back to normal. I don't know how the above line is added into nhc.conf. I looked at nhc-genconf file but couldn't find out reason either.

When I first created the cluster we use the same ansible code to install nhc, and the nodes does not contain that /run/user/1000 in nhc.conf. All the nodes are create using the same Centos image.

Appreciate if you could help 

Thanks very much,
Yi

**Comment by mej** [comment]
This "issue" isn't a bug but rather a general/usage question.  Those are probably best posted to the mailing list (nhc@lbl.gov or https://groups.google.com/a/lbl.gov/forum/#!forum/nhc) rather than here.  There are lots of folks there who can help!  :-)

My guess would be that you, or someone, ran `nhc-genconf` on those particular nodes when the user with UID 1000 happened to be logged in.  SystemD mounts user-specific `/run` directories for each user when they log in and unmounts them when the user logs out.  `nhc-genconf` has no way of knowing in advance which filesystems you will or won't care about, and since it's always easier to remove unneeded entries than it is to add them, it errs on the side of including everything, assuming that you'll get rid of the stuff you don't want/need.

I recommend you follow @OleHolmNielsen's advice on the `slurm-dev` mailing list:  Only run `nhc-genconf` _once_ on a single representative node for each type of node you have, merge them all into a single `nhc.conf` file, and then use that file everywhere.  And don't use it blindly; you'll want to remove any entries you don't care about (and probably add some others you do)!  :-)

Hope that helps!

**Comment by sunyi000** [comment]
Thank you Michael.  Really appreciate your help. Sorry for posting this to the wrong place. 

Regards,
Yi

**Comment by mej** [comment]
No worries at all!  I hope the above was helpful; feel free to follow up on the mailing list, or via Slack or Gitter if those are preferable avenues of communication for you.  :-)
