### ISSUE TITLE
Variables in nhcmain_init_env() parameters not being updated according to configure parameters 

### ISSUE THREAD

**Issue by mbelgin** [mej/nhc#34]
I'm not sure this is a really a bug, it's possible that I'm missing how the mechanism works. I'm configuring nhc as follows:

`./configure --prefix=${basepath} --sysconfdir=${basepath}/etc --libexecdir=${basepath}/libexec`

"make install" moves the bits in correct path, specified by $basepath, as designed. I'd expect, however,  that the nhcmain_init_env() function in nhc would also use these locations, but I'm still seeing the default paths embedded in the code:

```
SYSCONFIGDIR="/etc/sysconfig"
LIBEXECDIR="/usr/libexec" 
```

Old nhc versions included a "BASEDIR" variable, which is no longer in the nhc code.

Thanks!

**Comment by mej** [comment]
This is more or less intentional.  In order to have those values replaced by `./configure`, I'd have to have the script be called `nhc.in` in the source code rather than `nhc`, and `./configure` would then generate `nhc` from `nhc.in`.  GNU Autotools have historically not been reliable at preserving permissions properly when doing this, so I couldn't guarantee that the resulting `nhc` would be executable.  Nor did I particularly enjoy the notion of having to remember to make my changes to `nhc.in` all the time and leave `nhc` alone.

The values for `${LIBEXECDIR}` and `${CONFDIR}` are meant to be manipulated via `/etc/sysconfig/nhc` (or `/etc/sysconfig/${NAME}` to be more precise); the use of Autotools for NHC is strictly a packaging convenience.  (Take a look at how little is actually in `configure.ac`; you'll see what I mean!)

**Comment by mbelgin** [comment]
Thank you for the details Michael! I actually had to run configure multiple times until I realized that the short output is not a problem but by design ;) We really don't want to put anything under /etc, but I can always use symlinks.

**Comment by mej** [comment]
That's certainly a valid concern; I'm afraid that I wussed out a bit in that regard.  To avoid potential confusion and opportunity for "operator error," I wanted the bootstrap config location to be in a fixed spot for anyone who wasn't willing & able to hand-modify or patch the code on their own.  Since I'm most familiar with RedHat/Fedora/RHEL-like systems, the "standard" location for fixed global per-package customizations is `/etc/sysconfig`, so that's what I chose.

Keep in mind that NHC allows for complete customization of literally ANY variable on the command line, and parsing CLI options is the very first thing that happens after `nhcmain_init_env()`, so you can alter any configuration parameters you want -- even `$SYSCONFIGDIR` -- by specifying them on the command line, like so:

``` bash
# nhc SYSCONFIGDIR=/opt/nhc/1.4.2/sysconfig LIBEXECDIR=/opt/nhc/1.4.2/libexec CONFDIR=/opt/nhc/1.4.2/etc
```

See [Command-Line Invocation](https://github.com/mej/nhc#command-line-invocation) and [Supported Variables](https://github.com/mej/nhc#supported-variables) for details.

If that gets cumbersome, you could even rename `nhc` to `nhc.orig` and create a wrapper in, e.g. `/opt/nhc/1.4.2/bin/nhc`, that contained something like this:

``` bash
#!/bin/bash
PREFIX="${0%/*}"
PREFIX="${PREFIX%/*}"
exec $0.orig SYSCONFIGDIR="$PREFIX/sysconfig" LIBEXECDIR="$PREFIX/libexec" CONFDIR="$PREFIX/etc" "$@"
```

I haven't tested the above, so proceed with caution, but something like that ought to alleviate the issue. :-)
