### ISSUE TITLE
NHC seems to be ignoring 'NHC_RM=slurm' in nhc.conf

### ISSUE THREAD

**Issue by mbelgin** [mej/nhc#35]
Hi Michael, 

I've added this line in nhc.conf to use slurm as the RM:

`* || export NHC_RM=slurm`

However, NHC still seems to be checking /var/spool/torque (which also exists on our systems), and deciding that we must be using torque:

```
nhc -x -c /etc/nhc/nhc.conf | grep NHC_RM
...
+ local -a DIRLIST
+ [[ -d /var/spool/torque ]]
+ NHC_RM=pbs
+ return 0
...
(truncated)
```

to confirm: 

```
# grep NHC_RM /etc/nhc/nhc.conf
   * || export NHC_RM=slurm
```

Is this by design or a bug? I'd think once explicitly defined in nhc.conf, nhc would not need to perform any further checks to identify the RM... Skipping this check would also save some cycles ;)

Thanks!

**Comment by mbelgin** [comment]
Update: I moved "/var/spool/torque" out of the way, this time I'm seeing 

`dbg 'Unable to detect resource manager.'`

what am I missing?

**Comment by mej** [comment]
Lines in the config file aren't read right away; there's a lot of initialization and such that happens first.  And even after the config file gets read and the check lines loaded into memory, they still don't get executed until after the whole file has been read in, the watchdog timer forked off, etc.  Running all the checks is the very last thing that happens, apart from onlining/offlining nodes (if `$MARK_OFFLINE` is set).

I should probably add a flowchart to the docs that illustrates the program flow.  A lot of folks get tripped up by this.

Another thing that happens early on, long before the checks get run, is auto-detection of the RM.  That's why you're still seeing it get set to TORQUE, at least initially.  It should still get set to SLURM when the checks run, so if that's not happening, that *is* a bug.

However, if you need it to happen earlier, you can add it to the command line or the `/etc/sysconfig/nhc` file.  Either of those will enable it to get set before the auto-detection would otherwise happen.

**Comment by mbelgin** [comment]
You're right, I added a debug line to confirm that slurm is indeed being detected, however nodes are still not being offlined by NHC. I added this line in the "die" function: 

`syslog "DEBUG $NHC_RM , $MARK_OFFLINE , $OFFLINE_NODE "`

then created an artificial memory issue (checked for 10g min) and seeing the following output in the syslog:

```
Jun 12 17:58:39 devel-vcomp2 nhc[38345]: Health check failed:  check_hw_mem_free:  Not enough free memory (7575360 kB < 10485760 kB).
Jun 12 17:58:39 devel-vcomp2 nhc[38345]: DEBUG slurm , 0 , :
```
So, MARK_OFFLINE is not set, despite the failed check. This is probably not a bug and I must be missing something, so please let me know if you'd like to take this offline. Thanks Michael!

**Comment by mej** [comment]
If NHC fails to locate a resource manager it recognizes, it will unset `$MARK_OFFLINE` so that it doesn't waste time or generate bogus log messages trying to talk to an RM that isn't there.  So if you manually set `$NHC_RM`, you also need to manually set `$MARK_OFFLINE` if you want it to be used.  It may or may not be set to `1` by default, depending on what auto-detection does, but it's safest to force it to be `1`.

**Comment by mbelgin** [comment]
I'm starting to believe this is all due to sinfo not reporting the node status correctly. The node-offline script uses sinfo with these arguments:

```
[root@devel-vcomp1 nhc]# sinfo -o '%t %E' -hn `hostname`
[root@devel-vcomp1 nhc]#    (NOTHING)
```
which returns blank for the newly released slurm 17.02.4 (I haven't tested with older versions). The same command without the formatting bits returns a meaningful status, however:

```
[root@devel-vcomp1 nhc]# sinfo -hn `hostname`
test         up   infinite      0    n/a
vtest*       up   infinite      0    n/a
```
If you have access to a different version of slurm, would you please give the formatter output a try? This may very well be a Slurm bug.

**Comment by mbelgin** [comment]
Please discard the last comment, I wasn't using the short hostname. sinfo seems to be OK.

**Comment by mej** [comment]
You may want to check out the part under [TORQUE Integration](https://github.com/mej/nhc#torque-integration) about hostname mismatches; this also applies to SLURM.  If your nodes are set to FQDNs but SLURM only knows the short names, and you haven't set up aliases in SLURM for them, NHC won't be able to online/offline them correctly.

**Comment by mbelgin** [comment]
Ah, yes, all started working after:

`* || HOSTNAME="$HOSTNAME_S" `

Thanks for the link and all your help.
