### ISSUE TITLE
Detect appropriate location for SYSCONFDIR and LIBEXECDIR

### ISSUE THREAD

**Issue by mehdid** [mej/nhc#38]
Location for SYSCONFDIR and LIBEXECDIR may vary between Linux distributions. The patch below adds detection for Debian systems and sets paths for SYSCONFDIR and LIBEXECDIR accordingly.

https://github.com/edf-hpc/warewulf-nhc/blob/master/debian/patches/0001-Detect-debian-path-for-SYSCONFDIR-and-LIBEXECDIR.patch

**Comment by mej** [comment]
Thanks for your interest in contributing to NHC!  :-)

Unfortunately there are a couple issues with your proposed patch.

First, for reasons of performance and reliability, I keep any and all unnecessary subshells and subcommand executions out of the NHC code, so shelling out to `lsb_release` to determine if it's running on a Debian system isn't something I can accept.  Code to look for a Debian-specific file (such as `/etc/redhat-release` on RedHat systems) would be acceptable and is pretty easily done.

Second, the path for `LIBEXECDIR` in your patch is incorrect.  `/usr/libexec` is part of the [Filesystem Hierarchy Standard (FHS)](https://refspecs.linuxfoundation.org/FHS_3.0/fhs-3.0.html) specifically for [binaries/scripts executed by programs as opposed to users](https://refspecs.linuxfoundation.org/FHS_3.0/fhs-3.0.html#usrlibexec) and should be present on Debian systems; furthermore, specifying an application-specific subdirectory in `$LIBEXECDIR` is an error since the only variable that references it, `$HELPERDIR`, already adds the application-specific path `/nhc` to `$LIBEXECDIR`, so you'd end up with `$HELPERDIR` being set to `/usr/lib/warewulf-nhc/nhc` which is obviously incorrect.  (Also, NHC has not been part of the Warewulf project for quite some time now! :-) )  If you have a strong preference for `/usr/lib/nhc` over `/usr/libexec/nhc`, then `$LIBEXECDIR` should instead be set to `/usr/lib` rather than `/usr/lib/warewulf-nhc` (or `/usr/lib/nhc`).

**Comment by mehdid** [comment]
I'll into account your remarks and provide an updated patch. Though `/usr/libexec` doesn't exist on Debian systems so I'd stick to `/usr/lib` if that's okay for you. So, to summarize, the changes to the patch are:

- Check for existence of `/etc/debian_version` instead of calling `lsb_release`
- Use `/usr/lib` as `$LIBEXECDIR` instead of `/usr/lib/warewulf-nhc`.

**Comment by mej** [comment]
Fixed by @basvandervlies in 86b80f4 by #56.  Closing this issue.
