### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by sterni1971** [mej/nhc#85]
Hello!

it would be nice if you could make a new release with the fixes from the last years

/Sven

**Comment by kcgthb** [comment]
Agreed! :)

**Comment by mej** [comment]
For what it's worth, I agree with you 110%!  Unfortunately, while I was told that the legal situation was resolved, that wound up not to be true.  I'm trying to get everything straightened out, but obviously it's taking longer than expected.

I hope to be able to get the new release out soon, and with any luck I can get the outstanding issues tackled in the process.  In the meantime, the `dev` branch is what we're running at Los Alamos on all our production systems, and it's been quite solid for us for some time now.  It's very close to what will eventually be the next release, largely for that reason. :-)

**Comment by wpoely86** [comment]
This issue is approving 2 years, any news? I see changes in master and dev from August 2020?

@mej What are the legal issue you are referring to?

Currently we're building our own custom version of nhc which some home-made patches and some patches from pull requests here. This is far from ideal (and time consuming). I would prefer to just use the upstream version. If time is an issue, we can look into helping out reviewing and merging PRs?

**Comment by heitorPB** [comment]
I'm also interested in a new release.

@mej, what can I do to help here?

**Comment by mick-t** [comment]
I am willing to help with this.

**Comment by mej** [comment]
If you have commented on #85 or #109, please check your e-mail.  If you don't have a relevant e-mail from me, I'd ask that you contact me privately (via e-mail or on GH) so I can correct the error.

😃

**Comment by mej** [comment]
Since 1.4.3 has been released, and versions 1.4.4 and 1.5 are both well on their way, I'm closing this. 😁
