### ISSUE TITLE
Helper scripts custom path ignored in nhc

### ISSUE THREAD

**Issue by heitorPB** [mej/nhc#96]
During installation from source, the helper scripts (`node-mark-{on,off}line`)  are installed in the path `./configure`d with `--libexecdir`. But the `nhc` script looks for them `/usr/lib/nhc` (if debian-like), or `/usr/libexec/nhc` (otherwise), see 

There should be a way to set the `libexecdir` for a custom directory, as it can be set to a custom path. Maybe in `nhc.conf`?

**Comment by mej** [comment]
As noted in #62 and #63, NHC's `./configure`/`./autogen.sh` directory path options (e.g., `--libexecdir`) do not currently affect its config files' path variables (such as `${LIBEXECDIR}`).  So I'm going to close this issue as a duplicate in favor of #63; you can keep track of progress there. :smile_cat: 

As far as setting NHC config variables, you absolutely can.  Keep in mind, though, that as the [config variables table](https://github.com/mej/nhc/#supported-variables) warns, the relevant variables (`${HELPERDIR}` and `${INCDIR}`) can only be altered via `/etc/sysconfig/nhc` or CLI options due to the fact that they're used before the config file gets processed.  The helper scripts are loaded from, as you can probably guess, `${HELPERDIR}`, so if you put `HELPERDIR=<your-libexec-dir>/nhc` in `/etc/sysconfig/nhc`, you'll get the desired effect. :smiley:
